# Generated by Django 4.2.14 on 2024-07-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='challenge',
            field=models.SlugField(default='a_slug'),
        ),
    ]
